steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/local-sidekick/api', './server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/local-sidekick/api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'local-sidekick-api'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/local-sidekick/api'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
substitutions:
  _REGION: asia-northeast1
